/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
 
/**
 *
 * @author diana
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();

        btnTramitePlacas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear instancia de la clase TramitePlacas
                TramitePlacas tramitePlacas = new TramitePlacas();
                // Hacer visible la instancia creada
                tramitePlacas.setVisible(true);
                // Cerrar la ventana actual (Inicio)
                dispose();
            }
        });
        // ActionListener para el botón TramiteLicencia
        btnTramiteLicencia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear instancia de la clase TramiteLicencia
                TramiteLicencia tramite = new TramiteLicencia();
                // Hacer visible la instancia creada
                tramite.setVisible(true);
                // Cerrar la ventana actual (Inicio)
                dispose();
            }
        });
        // Agregar ActionListener al botón Consultas
        btnConsultas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear instancia de la clase Consultas
                Consultas consultas = new Consultas();
                // Hacer visible la instancia creada
                consultas.setVisible(true);
                // Cerrar la ventana actual (Inicio)
                dispose();
            }
        });
        // Agregar ActionListener al botón Reportes
        btnReportes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear instancia de la clase Reportes
                Reportes reportes = new Reportes();
                // Hacer visible la instancia creada
                reportes.setVisible(true);
                // Cerrar la ventana actual (Inicio)
                dispose();
            }
        });
        // Agregar ActionListener al botón InsertarPersonas
        btnInsertarPersonas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear instancia de la clase InsertarPersonas
                InsertarPersonas insertar = new InsertarPersonas();
                // Hacer visible la instancia creada
                insertar.setVisible(true);
                // Cerrar la ventana actual (Inicio)
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTramitePlacas = new javax.swing.JToggleButton();
        btnTramiteLicencia = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        btnConsultas = new javax.swing.JToggleButton();
        btnReportes = new javax.swing.JToggleButton();
        btnInsertarPersonas = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 118, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inicio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btnTramitePlacas.setBackground(new java.awt.Color(160, 11, 43));
        btnTramitePlacas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTramitePlacas.setForeground(new java.awt.Color(255, 255, 255));
        btnTramitePlacas.setText(" Tramite de placas");
        btnTramitePlacas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTramitePlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitePlacasActionPerformed(evt);
            }
        });
        jPanel1.add(btnTramitePlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 50));

        btnTramiteLicencia.setBackground(new java.awt.Color(160, 11, 43));
        btnTramiteLicencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTramiteLicencia.setForeground(new java.awt.Color(255, 255, 255));
        btnTramiteLicencia.setText("Tramite de licencia");
        btnTramiteLicencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTramiteLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramiteLicenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTramiteLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 190, 50));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(218, 184, 87));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(218, 184, 86));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 60));

        btnConsultas.setBackground(new java.awt.Color(160, 11, 43));
        btnConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultas.setText("Consultas");
        btnConsultas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 190, 50));

        btnReportes.setBackground(new java.awt.Color(160, 11, 43));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 190, 50));

        btnInsertarPersonas.setBackground(new java.awt.Color(160, 11, 43));
        btnInsertarPersonas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInsertarPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertarPersonas.setText("Insertar personas");
        btnInsertarPersonas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnInsertarPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\logo_secretarias_small_invert.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 210, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnTramitePlacasActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnTramiteLicenciaActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        TramiteLicencia tramite = new TramiteLicencia();
        // Hacer visible la instancia creada
        tramite.setVisible(true);
        // Cerrar la ventana actual (Inicio)
        dispose();
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton btnConsultas;
    private javax.swing.JToggleButton btnInsertarPersonas;
    private javax.swing.JToggleButton btnReportes;
    private javax.swing.JToggleButton btnTramiteLicencia;
    private javax.swing.JToggleButton btnTramitePlacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
