/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacion;

import DAOS.PersonaDAO;
import entidadesJPA.Persona;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author diana
 */
public class InsertarPersonas extends javax.swing.JFrame {

    /**
     * Creates new form InsertarPersonas
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public InsertarPersonas() {
        initComponents(); // Agrega esta línea para inicializar los componentes de la interfaz
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtRFC = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        RFC = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        botonAgregarPersona = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        txtRFC1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JLabel();
        txtNacimiento1 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JLabel();
        Telefono1 = new javax.swing.JTextField();
        RFC1 = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JTextField();
        Nacimiento1 = new javax.swing.JTextField();
        botonAgregarPersona1 = new javax.swing.JButton();
        botonRegresar1 = new javax.swing.JButton();
        curp = new javax.swing.JTextField();
        txtCurp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 118, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Insertar Personas ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField1.setBackground(new java.awt.Color(218, 184, 87));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 60));

        txtRFC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRFC.setText("RFC:");
        jPanel1.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNombre.setText("Nombre: ");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
        jPanel1.add(RFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 280, 30));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 280, 30));

        botonAgregarPersona.setBackground(new java.awt.Color(160, 11, 43));
        botonAgregarPersona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAgregarPersona.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarPersona.setText("Agregar Persona");
        botonAgregarPersona.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(botonAgregarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 180, -1));

        botonRegresar.setBackground(new java.awt.Color(160, 11, 43));
        botonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setText("Regresar");
        botonRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 180, 30));

        jPanel2.setBackground(new java.awt.Color(101, 118, 136));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insertar Personas ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField2.setBackground(new java.awt.Color(218, 184, 87));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 60));

        txtRFC1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRFC1.setText("RFC:");
        jPanel2.add(txtRFC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtNombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNombre1.setText("Nombre: ");
        jPanel2.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        txtNacimiento1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNacimiento1.setText("Nacimiento:");
        jPanel2.add(txtNacimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtTelefono1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTelefono1.setText("Telefono:");
        jPanel2.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        jPanel2.add(Telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 280, 30));
        jPanel2.add(RFC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 280, 30));
        jPanel2.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 280, 30));
        jPanel2.add(Nacimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 280, 30));

        botonAgregarPersona1.setBackground(new java.awt.Color(160, 11, 43));
        botonAgregarPersona1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAgregarPersona1.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarPersona1.setText("Agregar Persona");
        botonAgregarPersona1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAgregarPersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPersona1ActionPerformed(evt);
            }
        });
        jPanel2.add(botonAgregarPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 180, -1));

        botonRegresar1.setBackground(new java.awt.Color(160, 11, 43));
        botonRegresar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRegresar1.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar1.setText("Regresar");
        botonRegresar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresar1ActionPerformed(evt);
            }
        });
        jPanel2.add(botonRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 180, 30));
        jPanel2.add(curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 280, 30));

        txtCurp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCurp.setText("CURP:");
        jPanel2.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void botonAgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPersonaActionPerformed
        // Obtener los datos de los campos de texto y del JComboBox
        String rfc = RFC.getText();
        String nombreCompleto = Nombre.getText(); // Suponiendo que el campo Nombre contiene el nombre completo
        String[] partesNombre = nombreCompleto.split(" ");
        String nombre = "";
        String apellidoPaterno = "";
        String apellidoMaterno = "";
        String CURP = curp.getText();

        if (partesNombre.length >= 2) {
            nombre = partesNombre[0] + " " + partesNombre[1]; // Concatenar los dos primeros nombres
        }
        if (partesNombre.length >= 3) {
            apellidoPaterno = partesNombre[2]; // Suponiendo que la tercera parte es el apellido paterno
        }
        if (partesNombre.length >= 4) {
            apellidoMaterno = partesNombre[3]; // Suponiendo que la cuarta parte es el apellido materno
        }

        String EntidadNacimiento = curp.getText();
        Date fechaNacimiento = null;
        try {
            fechaNacimiento = new SimpleDateFormat("yyyy-MM-dd").parse(Nacimiento1.getText()); // Suponiendo que Nacimiento1 es un JTextField para la fecha
        } catch (ParseException ex) {
            // Manejar la excepción si la entrada no es un formato de fecha válido
            ex.printStackTrace();
        }

        String telefono = Telefono1.getText();

      
        // Crear una instancia de Persona con los datos obtenidos, incluyendo la CURP
        Persona persona = new Persona(rfc, nombre, apellidoPaterno, apellidoMaterno, fechaNacimiento, telefono, CURP);

        // Crear una instancia de PersonaDAO
        PersonaDAO personaDAO = new PersonaDAO();

        // Guardar la nueva persona en la base de datos
        personaDAO.guardarPersona(persona);
    }//GEN-LAST:event_botonAgregarPersonaActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void botonAgregarPersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPersona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarPersona1ActionPerformed

    private void botonRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nacimiento1;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField RFC;
    private javax.swing.JTextField RFC1;
    private javax.swing.JTextField Telefono1;
    private javax.swing.JButton botonAgregarPersona;
    private javax.swing.JButton botonAgregarPersona1;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonRegresar1;
    private javax.swing.JTextField curp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel txtCurp;
    private javax.swing.JLabel txtNacimiento1;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtRFC;
    private javax.swing.JLabel txtRFC1;
    private javax.swing.JLabel txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
