/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacion;

import DAOS.AutomovilDAO;
import DAOS.PlacaDAO;
import entidadesJPA.Automovil;
import entidadesJPA.Licencia;
import entidadesJPA.Persona;
import entidadesJPA.Placa;
import entidadesJPA.Tramite;
import java.util.Date;
import java.util.Random;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import negocio.LicenciaVigenteBO;

/**
 *
 * @author diana
 */
public class TramitePlacasNuevo extends javax.swing.JFrame {

    /**
     * Creates new form TramitePlacasNuevo
     */
    private EntityManager entityManager;
    private AutomovilDAO automovilDAO;
    private EntityManagerFactory entityManagerFactory;

    public TramitePlacasNuevo() {
        initComponents();
        automovilDAO = new AutomovilDAO();

        // Inicializar el EntityManagerFactory
        entityManagerFactory = Persistence.createEntityManagerFactory("ConexionPU");

        // Obtener el EntityManager
        entityManager = entityManagerFactory.createEntityManager();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        txtLinea = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        txtModelo = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        linea = new javax.swing.JTextField();
        numSerie = new javax.swing.JTextField();
        txtCosto = new javax.swing.JLabel();
        costo = new javax.swing.JTextField();
        botonRegresar = new javax.swing.JButton();
        botonRealizarTramite = new javax.swing.JButton();
        numLicencia = new javax.swing.JTextField();
        txtNumLicencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 118, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tramite de placas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 360, 40));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Automovil nuevo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 160, -1));

        jTextField1.setBackground(new java.awt.Color(218, 184, 87));
        jTextField1.setText("jTextField1");
        jTextField1.setMargin(new java.awt.Insets(101, 118, 136, 136));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 60));

        txtNumSerie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumSerie.setText("Num. Serie: ");
        jPanel1.add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        txtMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMarca.setText("Marca:");
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        txtLinea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLinea.setText("Linea:");
        jPanel1.add(txtLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        txtColor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtColor.setText("Color:");
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        txtModelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtModelo.setText("Modelo:");
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));
        jPanel1.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 280, 40));
        jPanel1.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 280, 40));
        jPanel1.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 280, 40));
        jPanel1.add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 280, 40));
        jPanel1.add(numSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 280, 40));

        txtCosto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCosto.setText("Costo:");
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, 30));

        costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoActionPerformed(evt);
            }
        });
        jPanel1.add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 90, 30));

        botonRegresar.setBackground(new java.awt.Color(160, 11, 43));
        botonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setText("Regresar");
        botonRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 180, 30));

        botonRealizarTramite.setBackground(new java.awt.Color(160, 11, 43));
        botonRealizarTramite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRealizarTramite.setForeground(new java.awt.Color(255, 255, 255));
        botonRealizarTramite.setText("Realizar Tramite");
        botonRealizarTramite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRealizarTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarTramiteActionPerformed(evt);
            }
        });
        jPanel1.add(botonRealizarTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 180, 30));
        jPanel1.add(numLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 280, 40));

        txtNumLicencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumLicencia.setText("Num. Licencia");
        jPanel1.add(txtNumLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void botonRealizarTramiteActionPerformed(java.awt.event.ActionEvent evt) {                                                     

        String numeroSerie = numSerie.getText();
        String marcaAutomovil = marca.getText();
        String lineaAutomovil = linea.getText();
        String colorAutomovil = color.getText();
        int modeloAutomovil = Integer.parseInt(modelo.getText());
        String numeroLicencia = numLicencia.getText(); // Obtener número de licencia ingresado

        // Obtener una instancia de EntityManager (debe ser inicializada previamente)
        EntityManager entityManager = obtenerEntityManager();

        if (entityManager != null) {
            // Crear instancia de LicenciaVigenteBO
            LicenciaVigenteBO licenciaBO = new LicenciaVigenteBO(entityManager);

            // Obtener la licencia vigente
            Licencia licencia = licenciaBO.obtenerLicenciaVigente(numeroLicencia);

            // Verificar si la licencia obtenida es nula
            if (licencia != null) {
                // Obtener la persona asociada a la licencia

                Persona persona = licencia.getPersona();
                if (persona != null) {
                    // Crear instancia de Automovil y establecer sus atributos
                    Automovil automovil = new Automovil();
                    automovil.setNumeroSerie(numeroSerie);
                    automovil.setMarca(marcaAutomovil);
                    automovil.setLinea(lineaAutomovil);
                    automovil.setColor(colorAutomovil);
                    automovil.setModelo(modeloAutomovil);

                    PlacaDAO placaDAO = new PlacaDAO();
                    placaDAO.desactivarPlacasActivas(automovil);

                    // Generar número de placas alfanumérico
                    String numeroPlacas = generarNumeroPlacas();

                    AutomovilDAO auto = new AutomovilDAO();
                    auto.guardarAutomovil(automovil);

                    // Crear una nueva instancia de Placa y establecer sus atributos
                    Placa nuevaPlaca = new Placa();
                    nuevaPlaca.setNumeroPlaca(numeroPlacas);
                    nuevaPlaca.setFechaEmision(new Date());
                    nuevaPlaca.setEstado("Activo");
                    nuevaPlaca.setAutomovil(automovil);
                    nuevaPlaca.setCosto(1500.00f);
                    PlacaDAO placa = new PlacaDAO();
                    placa.guardarPlaca(nuevaPlaca);

                    // Crear una nueva instancia de Tramite y establecer su automovil
                    Tramite nuevoTramite = new Tramite();
                    nuevoTramite.setFechaTramite(new Date());
                    nuevoTramite.setTipoTramite("Nuevo");
                    nuevoTramite.setCosto(1500.00f);
                    nuevoTramite.setPersona(persona);

                    // Persistir el nuevo tramite en la base de datos
                    entityManager.getTransaction().begin();
                    entityManager.persist(nuevoTramite);
                    entityManager.getTransaction().commit();

                    JOptionPane.showMessageDialog(this, "Trámite realizado con éxito.");
                } else {
                    JOptionPane.showMessageDialog(this, "La licencia no tiene una persona asociada.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró una licencia vigente en el sistema.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al obtener el EntityManager.");
        }
        
        costo.setEditable(false);
    
    }                                                    

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {                                              

        dispose();

        // Crear una nueva instancia de la clase Inicio y hacerla visible
        new Inicio().setVisible(true);
    }                                             

    private void costoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        // Establecer el costo del automóvil en el campo de texto correspondiente
    costo.setText(String.valueOf(1500.00f)); // Costo fijo de $1500.00
    }                                     

    private EntityManager obtenerEntityManager() {
        return entityManager;
    }

    private String generarNumeroPlacas() {
        Random random = new Random();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 3; i++) {
            char c = (char) (random.nextInt(26) + 'A');
            sb.append(c);
        }
        sb.append("-");
        for (int i = 0; i < 3; i++) {
            int digit = random.nextInt(10);
            sb.append(digit);
        }
        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonRealizarTramite;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField color;
    private javax.swing.JTextField costo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField linea;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField numLicencia;
    private javax.swing.JTextField numSerie;
    private javax.swing.JLabel txtColor;
    private javax.swing.JLabel txtCosto;
    private javax.swing.JLabel txtLinea;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JLabel txtModelo;
    private javax.swing.JLabel txtNumLicencia;
    private javax.swing.JLabel txtNumSerie;
    // End of variables declaration                   
}
