/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacion;

import entidadesJPA.Automovil;
import DAOS.AutomovilDAO;
import DAOS.PlacaDAO;
import DAOS.TramiteDAO;
import entidadesJPA.Licencia;
import entidadesJPA.Persona;
import entidadesJPA.Placa;
import entidadesJPA.Tramite;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import negocio.LicenciaVigenteBO;

/**
 *
 * @author diana
 */
public class TramitePlacasUsado extends javax.swing.JFrame {

    private EntityManager entityManager;
    private AutomovilDAO automovilDAO;
    private PlacaDAO placaDAO;

    public TramitePlacasUsado() {
        initComponents();
        automovilDAO = new AutomovilDAO();
        placaDAO = new PlacaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtNumPlaca = new javax.swing.JLabel();
        Linea = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        txtNumSerie = new javax.swing.JLabel();
        NumPlaca = new javax.swing.JTextField();
        txtMarca = new javax.swing.JLabel();
        NumSerie = new javax.swing.JTextField();
        txtLinea = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        txtCosto = new javax.swing.JLabel();
        Costo = new javax.swing.JTextField();
        botonRealizarTramite = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        NumLicencia = new javax.swing.JTextField();
        txtLinea1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 118, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tramite de placas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Automovil Usado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jTextField1.setBackground(new java.awt.Color(218, 184, 87));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 60));

        txtNumPlaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumPlaca.setText("Num. Placa:");
        jPanel1.add(txtNumPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));
        jPanel1.add(Linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 270, 30));

        botonBuscar.setBackground(new java.awt.Color(160, 11, 43));
        botonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setText("Buscar");
        botonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 110, 30));

        txtNumSerie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumSerie.setText("Num. Serie:");
        jPanel1.add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 90, 20));

        NumPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(NumPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 30));

        txtMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMarca.setText("Marca: ");
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 90, 30));
        jPanel1.add(NumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 270, 30));

        txtLinea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLinea.setText("Linea:");
        jPanel1.add(txtLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 90, 30));
        jPanel1.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 270, 30));

        txtCosto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCosto.setText("Costo:");
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));
        jPanel1.add(Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        botonRealizarTramite.setBackground(new java.awt.Color(160, 11, 43));
        botonRealizarTramite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRealizarTramite.setForeground(new java.awt.Color(255, 255, 255));
        botonRealizarTramite.setText("Realizar Tramite");
        botonRealizarTramite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRealizarTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarTramiteActionPerformed(evt);
            }
        });
        jPanel1.add(botonRealizarTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 180, 30));

        botonRegresar.setBackground(new java.awt.Color(160, 11, 43));
        botonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setText("Regresar");
        botonRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 150, 30));
        jPanel1.add(NumLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 270, 30));

        txtLinea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLinea1.setText("Num. Licencia:");
        jPanel1.add(txtLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumPlacaActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String numSerie = NumSerie.getText();

        // Obtener la lista de automóviles que coinciden con el número de serie
        List<Automovil> automoviles = automovilDAO.obtenerAutomovilPorNumeroSerieLista(numSerie);

        if (!automoviles.isEmpty()) {
            // Crear un arreglo de cadenas para almacenar la información de los automóviles
            String[] opciones = new String[automoviles.size()];
            int i = 0;
            for (Automovil automovil : automoviles) {
                opciones[i++] = automovil.toString(); // Suponiendo que tienes un método toString en la clase Automovil para mostrar la información relevante
            }

            // Mostrar los resultados en un JOptionPane de tipo lista
            String seleccion = (String) JOptionPane.showInputDialog(null, "Selecciona un automóvil:", "Automóviles encontrados",
                    JOptionPane.DEFAULT_OPTION, null, opciones, opciones[0]);

            // Si se selecciona un automóvil, mostrar sus detalles en los campos correspondientes
            if (seleccion != null) {
                // Aquí puedes realizar las acciones necesarias para mostrar los detalles del automóvil seleccionado
            }
        } else {
            // Si no se encontró ningún automóvil, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "No se encontró ningún automóvil con el número de serie proporcionado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonRealizarTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarTramiteActionPerformed
        // Obtener los datos ingresados por el usuario
        String numSerie = NumSerie.getText();
        EntityManager entityManager = obtenerEntityManager();

        Automovil automovil = automovilDAO.obtenerAutomovilPorNumeroSerie(numSerie);
        if (automovil == null) {
            JOptionPane.showMessageDialog(this, "El automóvil no está registrado en el sistema.");
            return;
        }

        // Verificar la licencia vigente del usuario
        String numLicencia = NumLicencia.getText();
        LicenciaVigenteBO licenciaBO = new LicenciaVigenteBO(entityManager); // Necesitas implementar esta clase
        Licencia licencia = licenciaBO.obtenerLicenciaVigente(numLicencia);

        // Crear una instancia de Tramite
        Tramite tramite = new Tramite();
        tramite.setFechaTramite(new Date());
        tramite.setCosto(1000.00f);
        Persona persona = licencia.getPersona();
        tramite.setPersona(persona);
        TramiteDAO tramiteDAO = new TramiteDAO();
        tramiteDAO.guardarTramite(tramite);

        if (licencia == null) {
            JOptionPane.showMessageDialog(this, "La licencia ingresada no es válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear una nueva instancia de Placa y establecer los datos necesarios
        Placa nuevaPlaca = new Placa();
        nuevaPlaca.setNumeroPlaca(generarNumeroPlacas()); // Generar un nuevo número de placa
        nuevaPlaca.setFechaEmision(new Date()); // Establecer la fecha de emisión como la fecha actual
        nuevaPlaca.setCosto(1000.00f);

        // Realizar el trámite de placas para el automóvil
        placaDAO.guardarPlaca(nuevaPlaca);

        // Mostrar un mensaje de éxito al usuario
        JOptionPane.showMessageDialog(this, "El trámite de placas se realizó exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Limpiar los campos de la interfaz o realizar otras acciones según sea necesario
        limpiarCampos();
    }//GEN-LAST:event_botonRealizarTramiteActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed

        dispose();

        // Crear una nueva instancia de la clase Inicio y hacerla visible
        new Inicio().setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private EntityManager obtenerEntityManager() {
        return entityManager;
    }

    private void limpiarCampos() {
        // Código para limpiar los campos de la interfaz después de realizar el trámite
        NumPlaca.setText("");
        NumSerie.setText("");
        Marca.setText("");
        Linea.setText("");
        // También puedes limpiar otros campos si es necesario
    }

    private String generarNumeroPlacas() {
        Random random = new Random();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 3; i++) {
            char c = (char) (random.nextInt(26) + 'A');
            sb.append(c);
        }
        sb.append("-");
        for (int i = 0; i < 3; i++) {
            int digit = random.nextInt(10);
            sb.append(digit);
        }
        return sb.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Costo;
    private javax.swing.JTextField Linea;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField NumLicencia;
    private javax.swing.JTextField NumPlaca;
    private javax.swing.JTextField NumSerie;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonRealizarTramite;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txtCosto;
    private javax.swing.JLabel txtLinea;
    private javax.swing.JLabel txtLinea1;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JLabel txtNumPlaca;
    private javax.swing.JLabel txtNumSerie;
    // End of variables declaration//GEN-END:variables
}
