/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacion;



/**
 *
 * @author diana
 */
public class TramitePlacasNuevo extends javax.swing.JFrame {

    /**
     * Creates new form TramitePlacasNuevo
     */
     private String datosIngresados;
   
    public TramitePlacasNuevo() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        txtLinea = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        txtModelo = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        linea = new javax.swing.JTextField();
        numSerie = new javax.swing.JTextField();
        txtCosto = new javax.swing.JLabel();
        costo = new javax.swing.JTextField();
        botonRegresar = new javax.swing.JButton();
        botonRealizarTramite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 118, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tramite de placas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 360, 40));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Automovil nuevo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 160, -1));

        jTextField1.setBackground(new java.awt.Color(218, 184, 87));
        jTextField1.setText("jTextField1");
        jTextField1.setMargin(new java.awt.Insets(101, 118, 136, 136));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 60));

        txtNumSerie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumSerie.setText("Num. Serie: ");
        jPanel1.add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMarca.setText("Marca:");
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        txtLinea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLinea.setText("Linea:");
        jPanel1.add(txtLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        txtColor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtColor.setText("Color:");
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        txtModelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtModelo.setText("Modelo:");
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));
        jPanel1.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 280, 40));
        jPanel1.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 280, 40));
        jPanel1.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 280, 40));
        jPanel1.add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 280, 40));
        jPanel1.add(numSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 280, 40));

        txtCosto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCosto.setText("Costo:");
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));
        jPanel1.add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        botonRegresar.setBackground(new java.awt.Color(160, 11, 43));
        botonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setText("Regresar");
        botonRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 180, 30));

        botonRealizarTramite.setBackground(new java.awt.Color(160, 11, 43));
        botonRealizarTramite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRealizarTramite.setForeground(new java.awt.Color(255, 255, 255));
        botonRealizarTramite.setText("Realizar Tramite");
        botonRealizarTramite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(botonRealizarTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRealizarTramite;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField color;
    private javax.swing.JTextField costo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField linea;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField numSerie;
    private javax.swing.JLabel txtColor;
    private javax.swing.JLabel txtCosto;
    private javax.swing.JLabel txtLinea;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JLabel txtModelo;
    private javax.swing.JLabel txtNumSerie;
    // End of variables declaration//GEN-END:variables
}
