/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author diana
 */
public class TramitePlacasUsado extends javax.swing.JFrame {

    /**
     * Creates new form TramiteLicenciaUsado
     */
    // Variable para almacenar los datos
    private String datosIngresados;

// Método para guardar los datos en un archivo de texto
    private void guardarDatosEnArchivo(String datos) {
    try {
        FileWriter fileWriter = new FileWriter("datos_placas_usado.txt");
        BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
        bufferedWriter.write(datos);
        bufferedWriter.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
   }

    public TramitePlacasUsado() {
        initComponents();
        // Agregar ActionListener al botón Regresar
        Regresar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear instancia del JFrame TramitePlacas
                TramitePlacas tramitePlacas = new TramitePlacas();
                // Hacer visible la instancia creada
                tramitePlacas.setVisible(true);
                // Cerrar la ventana actual (TramitePlacasNuevo)
                dispose();
            }
        });
        // Agregar ActionListener al botón Realizar Tramite
     RealizarTramite.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        // Capturar los datos ingresados en las variables correspondientes
        String numPlaca = NumPlaca.getText();
        String numSerie = NumSerie.getText();
        String marca = Marca.getText();
        String linea = Linea.getText();
        String costo = Costo.getText();

        // Crear una cadena con los datos ingresados
        datosIngresados = "Número de Placa: " + numPlaca + "\n" +
                         "Número de Serie: " + numSerie + "\n" +
                         "Marca: " + marca + "\n" +
                         "Línea: " + linea + "\n" +
                         "Costo: " + costo + "\n";

        // Llamar al método para guardar los datos en un archivo de texto
        guardarDatosEnArchivo(datosIngresados);

        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(null, "Datos guardados correctamente en datos_placas_usado.txt");

        // Cerrar la ventana actual (TramitePlacasUsado)
        dispose();
    }
    });
    // Agregar ActionListener al botón Realizar Tramite
    RealizarTramite.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        // Capturar los datos ingresados en las variables correspondientes
        String numPlaca = NumPlaca.getText();
        String numSerie = NumSerie.getText();
        String marca = Marca.getText();
        String linea = Linea.getText();
        String costo = Costo.getText();

        // Crear una cadena con los datos ingresados
        datosIngresados = "Número de Placa: " + numPlaca + "\n" +
                         "Número de Serie: " + numSerie + "\n" +
                         "Marca: " + marca + "\n" +
                         "Línea: " + linea + "\n" +
                         "Costo: " + costo + "\n";

        // Llamar al método para guardar los datos en un archivo de texto
        guardarDatosEnArchivo(datosIngresados);

        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(null, "Datos guardados correctamente en datos_placas_usado.txt");
    }
    });

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Linea = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NumPlaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NumSerie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Costo = new javax.swing.JTextField();
        RealizarTramite = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 118, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tramite de placas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Automovil Usado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jTextField1.setBackground(new java.awt.Color(218, 184, 87));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Num. Placa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));
        jPanel1.add(Linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 270, 30));

        jButton1.setBackground(new java.awt.Color(160, 11, 43));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 110, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Num. Serie:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 90, 20));

        NumPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(NumPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Marca: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, 30));
        jPanel1.add(NumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 270, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Linea:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 90, 30));
        jPanel1.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 270, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Costo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));
        jPanel1.add(Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        RealizarTramite.setBackground(new java.awt.Color(160, 11, 43));
        RealizarTramite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RealizarTramite.setForeground(new java.awt.Color(255, 255, 255));
        RealizarTramite.setText("Realizar Tramite");
        RealizarTramite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(RealizarTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 180, 30));

        Regresar.setBackground(new java.awt.Color(160, 11, 43));
        Regresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setText("Regresar");
        Regresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TramitePlacasUsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TramitePlacasUsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TramitePlacasUsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TramitePlacasUsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TramitePlacasUsado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Costo;
    private javax.swing.JTextField Linea;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField NumPlaca;
    private javax.swing.JTextField NumSerie;
    private javax.swing.JButton RealizarTramite;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
