/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacion;
 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author diana (Modificaciones: Antonio)
 */

public class TramiteLicencia extends javax.swing.JFrame {

    private String nombre;
    private String rfc;
    private String nacimiento;
    private String telefono;
    private String tiempoVigencia;
    private boolean tieneDiscapacidad;

    public TramiteLicencia() {
        initComponents();

        // ActionListener para el BotonNombre
        textFieldNombre.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                nombre = textFieldNombre.getText();
            }
        });

        // ActionListener para el  BotonRFC
        textFieldRFC.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                rfc = textFieldRFC.getText();
            }
        });

        JDCNacimiento.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if ("date".equals(evt.getPropertyName())) {
                    // Obtener la fecha seleccionada
                    Date selectedDate = JDCNacimiento.getDate();
                    // Formatear la fecha en el formato deseado (dd/MM/yyyy)
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    nacimiento = sdf.format(selectedDate);
                }
            }
        });

        // ActionListener para el ComboBox TiempoVigencia
        TiempoVigencia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tiempoVigencia = (String) TiempoVigencia.getSelectedItem();
                actualizarCosto(); // Llamar al método actualizarCosto() cuando cambia la selección
            }
        });

// ActionListener para el ComboBox Discapacidad
        Discapacidad.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String seleccion = (String) Discapacidad.getSelectedItem();
                tieneDiscapacidad = seleccion.equals("SI");
                actualizarCosto(); // Llamar al método actualizarCosto() cuando cambia la selección
            }
        });

    }

    private void actualizarCosto() {
        int costoNormal = 0;
        int costoDiscapacitados = 0;

        switch (tiempoVigencia) {
            case "1 AÑO":
                costoNormal = 600;
                costoDiscapacitados = 200;
                break;
            case "2 AÑOS":
                costoNormal = 900;
                costoDiscapacitados = 500;
                break;
            case "3 AÑOS":
                costoNormal = 1100;
                costoDiscapacitados = 700;
                break;
        }

        // Aplicar descuento en caso de discapacidad
        if (tieneDiscapacidad) {
            textFieldCosto.setText(String.valueOf(costoDiscapacitados));
        } else {
            textFieldCosto.setText(String.valueOf(costoNormal));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TiempoVigencia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Discapacidad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        textFieldCosto = new javax.swing.JTextField();
        Regresar = new javax.swing.JToggleButton();
        RealizarTramite = new javax.swing.JButton();
        textFieldRFC = new javax.swing.JTextField();
        textFieldNombre = new javax.swing.JTextField();
        textFieldTelefono = new javax.swing.JTextField();
        JDCNacimiento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 212, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel8.setText("Tramite de licencia");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jTextField2.setBackground(new java.awt.Color(204, 0, 51));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("RFC:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 37, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nacimiento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tiempo de vigencia:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, 20));

        TiempoVigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 AÑO", "2 AÑOS", "3 AÑOS" }));
        jPanel1.add(TiempoVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Discapacidad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        Discapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(Discapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Costo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        textFieldCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCostoActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 50, -1));

        Regresar.setBackground(new java.awt.Color(204, 0, 51));
        Regresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Regresar.setText("Regresar ");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 130, 30));

        RealizarTramite.setBackground(new java.awt.Color(204, 0, 51));
        RealizarTramite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RealizarTramite.setText("Realizar tramite");
        RealizarTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarTramiteActionPerformed(evt);
            }
        });
        jPanel1.add(RealizarTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 180, 30));

        textFieldRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRFCActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 260, 30));
        jPanel1.add(textFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 260, 30));

        textFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 260, 30));
        jPanel1.add(JDCNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void RealizarTramiteActionPerformed(java.awt.event.ActionEvent evt) {                                                
// Validar la longitud del número de teléfono
    String telefono = textFieldTelefono.getText().trim();
    if (telefono.length() != 10) {
        JOptionPane.showMessageDialog(null, "El número de teléfono debe tener 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
        textFieldTelefono.setText(""); // Limpiar el campo de texto
        textFieldTelefono.requestFocus(); // Poner el foco en el campo de texto para que el usuario pueda corregirlo
        return; // Salir del método si la validación del teléfono falla
    }

    // Si la validación del teléfono pasa, continuar con el proceso
    int costoFinal = Integer.parseInt(textFieldCosto.getText());

    // Mostrar el mensaje con el costo antes de confirmar el trámite
    JOptionPane.showMessageDialog(null, "El costo del trámite es: $" + costoFinal + "\nTrámite realizado con éxito");

    // Cerrar la ventana actual (TramiteLicencia)
    dispose();

    // Crear una nueva instancia de la clase Inicio y hacerla visible
    new Inicio().setVisible(true);
    }                                               

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {                                         
          // Cerrar la ventana actual (TramiteLicencia)
    dispose();

    // Crear una nueva instancia de la clase Inicio y hacerla visible
    new Inicio().setVisible(true);
    }                                        

    private void textFieldRFCActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void textFieldCostoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void textFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {                                                  

    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TramiteLicencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TramiteLicencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TramiteLicencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TramiteLicencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TramiteLicencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> Discapacidad;
    private com.toedter.calendar.JDateChooser JDCNacimiento;
    private javax.swing.JButton RealizarTramite;
    private javax.swing.JToggleButton Regresar;
    private javax.swing.JComboBox<String> TiempoVigencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField textFieldCosto;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldRFC;
    private javax.swing.JTextField textFieldTelefono;
    // End of variables declaration                   
}

